Refactor message chains
Software-Quality-UMM-CSci-4659-F18/smells-in-machine-shop-simulator-travis_shawn pull request #6
Opened 2018-09-25 20:54 UTC by GLOBBIMUS

Fixed message chain smell in the MachineShopSimulator.

We specifically fixed message chains in the setUpJobs, changeState, and moveToNextMachine methods.

2018-09-25 21:15 UTC, NicMcPhee reviewed
I left a few questions about just simple formatting. I didn't do anything with the actual refactoring.

2018-09-25 21:15 UTC, NicMcPhee commented on .idea/modules.xml
>        <module fileurl="file://$PROJECT_DIR$/.idea/Machine-shop-simulator.iml" filepath="$PROJECT_DIR$/.idea/Machine-shop-simulator.iml" />
You don't want all these IntelliJ IML files to be part of the pull request.

2018-09-25 21:15 UTC, NicMcPhee commented on src/applications/Job.java
> +
Do you want this blank line here?

2018-09-25 21:15 UTC, NicMcPhee commented on src/applications/Machine.java
> +
Do you want these blank lines?

2018-09-27 15:31 UTC, YujingSong reviewed
Though these are small changes, I can see that you efforts to remove chains and make the program easier to read, especially, I like your idea that change "p" to "machine number".   The chains didn't become shorter, but increase the coding readability.

2018-09-27 20:45 UTC, schon094 requested changes
Nice job creating variables in order to clean up the code. This increases readability, and makes the functions less repetitive.
Remove the IntelliJ IML files from the pull request, and clean up old comments and whitespace.
Good job creating methods in Job and Machine.java. This fixes several issues in addition to message chains, like data class or long class.  Adding Machine.setTotalWait() makes the MachineShopSimulator more readable and is a great solution to your message chain problem.

2018-09-27 21:03 UTC, YujingSong approved these changes
I like the way that you organize your code, but I am afraid that your documents are not clear enough, hope that will have more explanations about what you did in each issue.  Commit messages are good, refactoring is complete.

2018-09-30 22:29 UTC, rabex028 commented on src/applications/Job.java
> +    public int getMachineNumber(){
This is a nice change that definitely makes things more clear in line 36 of MachineShopSimulator.

2018-09-30 22:39 UTC, rabex028 commented on src/applications/SimulationSpecification.java
> +        return out;
The variable name out seems ambiguous to me.

2018-09-30 23:19 UTC, rabex028 approved these changes
I think substantial improvements were made in regard to the message chaining smell, especially in the changeState method. In general, I think the name refactorings have also helped add much needed clarity to the methods you have chosen to address. There are a few places that might benefit from some extra attention though in regard to naming in my opinion. For instance, the _removed_ variable on line 70 of MachineShopSimulator could be more specific about what is removed. Another variable which seems even more vague to me is the _out_ variable declared in line 36 of SimulationSpecification. Removing the iml files and unnecessary white space would probably also be good improvements to make before merging.

Apart from code changes, more elaboration in your pull request description (at least) might be helpful for reviewers in the future to give more meaningful feedback. Apart from these concerns I think that overall the codebase would definitely benefit from the changes you've made because the methods you focused on seem much more readable and clear about what they are doing to me.

2018-10-02 03:19 UTC, nickplucker approved these changes
I think you definitely reduced the amount of nasty message chains that exist and the code easier to read and understand. You also remove the entire message chain and you don't move it to another place. The commits are appropriately sized and the commit messages are clear.  I would, however, like to see a little more documentation regarding your pull request. It's clear that you addressed message chains but it would be nice to know *why* you did what you did. 
I would just remove the `.iml` and `.xml` files and your pull request looks set to merge! Nice work!

2018-10-04 05:19 UTC, leonidscott requested changes
Overall Good PR! :confetti_ball:  
You found a lot of good examples of message chaining and fixed *most* of them. The places you did fix had dramatic improvements in readability. Moreover, your PR actually deleted more lines than it created! That doesn't say much in and of itself, but typically writing really good code means deleting more than your write!  

You got a lot right, but you also didn't completely tidy up after your selves. Some areas for improvement, that I would like to see in this PR are:  
* **Fixing Message-chains instead of moving them:** You did a pretty good job of this, and when you did shift functionality of a message chain to a parent class, the code became drastically more readable. However, there are a couple places (mentioned in comments) where you just split up message chains into several lines. This might seem harmless, but it substantially hurts code readability. Instead of that message chain sticking out like a sore thumb read for refactoring, it now blends in. This is even when the message chain, in its full entirely is still right there! Moreover, writing variable names is super hard, and if you don't actually get any benefit from it, then you shouldn't. You know how to fix these message chains, you have done it before with great success!  
* **Continuing bad practices from the past:** The fact that the code has some terrible naming schemes, and practices, is not your fault... but it is your problem. That's why you shouldn't continue using variable names such as *the-blah*, or calling functions from a class that access private fields you already have access to.  
* **Whitespace:** Before you commit, be sure to check the diffs on your files to see if you left any whitespaces. You can do it in IntelliJ pretty easily, but you can also go to your command prompt and type in `git diff` for uncommitted files, or `git diff --staged` for already committed files.  
* **Committing more often:** You can't fix your previous git sins, but you can start committing more often now.  
* **Adding Issues to commits:** If your commit addresses a git issue, like every single ones of yours does, you should add a `[#<Insert Issue Number>]` at the front of your commit messages. This allows your reviews to go to your issue on github, and see, right underneath it, all the commits that address it. You can also add an `addresses [#<Issue Number]` to your PR description.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +
Remove whitespace

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +                eList.setFinishTime(theMachine, timeNow + removed);
This is a good example of a message chain but not a terribly great example of how to fix one. I would actually argue that this make the code *harder* for two reasons:  
* You now have to think a good variable name for the output of `currentMachine.getActiveJob`. I think you've done a good job of that though.  
* The chain doesn't look as bad, but it still is. The code is now less honest about how message chainy it is. That is a problem for future debugging.   

I think the solution to this message chain would be to create a function that abstracts this. To start this function might be a local helper function, but might end up in Machine. 

In addition, there is a second problem that isn't your fault, but is you problem: `removeNextTask()` both removes a task and returns a time. That is not intuitive and needs to be broken up in `machine`. I wouldn't worry about this during this refactoring, but it is probably the most cringy thing in that original line of code. But, it means that the output of `currentJob.removeNextTask()` is a time, not a removed Job; You should change that variable name to be something related to *time*.

2018-10-04 05:19 UTC, leonidscott commented on .idea/modules/Machine-shop-simulator_main.iml
>      <orderEntry type="sourceFolder" forTests="false" />
This file shouldn't be here

2018-10-04 05:19 UTC, leonidscott commented on .idea/modules/Machine-shop-simulator_test.iml
>        <sourceFolder url="file://$MODULE_DIR$/../../tests/properties" isTestSource="true" />
This file shouldn't be here

2018-10-04 05:19 UTC, leonidscott commented on .idea/modules/smells-in-machine-shop-simulator-travis_shawn.iml
> +</module>
This should be `.gitignore`ed

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Job.java
> +
Make sure to very intentional about white space in commits

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Job.java
> +        Object frontElement = taskQ.getFrontElement();
`Task frontElement = (task) taskQ.getFrontElement();`
Also frontElement isn't a great name. Maybe something like `firstTask` would be better.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Job.java
> +        return machineNum;
put `return` a line before

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Job.java
> +    public int getMachineNumber(){
This function serves a good purpose.

2018-10-04 05:19 UTC, leonidscott commented on .gitignore
> +.idea/
This is a good improvement

2018-10-04 05:19 UTC, leonidscott commented on .gitignore
> +*.ipr
This is a good improvement

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Job.java
> +        int machineNum = ((Task)frontElement).getMachine();
Remove typecasting

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Job.java
> +     * This method extracts the Machine number from the job
This is a pretty reasonable comment, what does `@return` do though? If it doesn't do anything, then just make this a single line comment.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +    public void putJob(Job theJob){
Don't use `theJob` as a variable name. You can call it `job`, or even `j`, just don't call it `theJob`; from the dawn of time that has been a bad variable name. It is a **Nasty** convention from the code you inherited, but you have a responsibility to make each class, method, and line of code you use or write better than when you left it.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +
Whitespace

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +    public void putJob(Job theJob){
I think perpetuates one of the bad smells in the code base from the start. `jobQ` is private, yet has public **put** and **get** functions; that kind of defeats the purpose of `jobQ` being private. I would argue that if you are going to create a *setter* for this datastructure, just make the datastructure public.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +        int delay = getTotalWait();
This line doesn't need to exist. `getTotalWait()` just access returns `totalWait`, a field at the top of class you are in. You could just bind `delay` to that field, or better yet, just use `totalWait` where you need it.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +        Job activeJob = getActiveJob();
This line doesn't need to exist. `getActiveJob()` just returns `activeJob`, a field at the top of the class that you have access to.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +        int arrivalTime = activeJob.getArrivalTime();
I don't think you really need this line

2018-10-04 05:19 UTC, leonidscott commented on src/applications/Machine.java
> +        this.totalWait = (delay + timeNow) - arrivalTime;
this should just be:
`this.totalWait = (totalWait + timeNow) - activeJob.getArrivalTime();`

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +import dataStructures.LinkedQueue;
Remove unused import

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +
White Space

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +            int machineNum = theJob.getMachineNumber();
This makes so much more sense now, good work!

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +            int machineNum = theJob.getMachineNumber();
It's also a much better variable name

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +            machine[machineNum].putJob(theJob);
This is much better

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +                changeState(machineNum);
The variable name change helps a lot

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +        Machine currentMachine = machine[theMachine];
Good use of splitting out the variable. Especially because it get's used in a bunch of places

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +            JobSpecification taskArray = specification.getJobSpecifications(i);
In the same vain as the previous comment, I don't like this line of code. I think the proper response is to add a function to `specification` that returns the number of tasks. 

Remember that variable names a super hard, and each one you make *has* to be a great one. In this case you don't really benefit from it because you don't use task Array anywhere else but the line below. The only real solution to breaking up a message chain, is to figure out what object owns the *message-chained* functionality, then put that logic there.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +            machine[firstMachine].putJob(theJob);
That message chain breaking works well

2018-10-04 05:19 UTC, leonidscott commented on src/applications/SimulationSpecification.java
> +    public int getSpecification(int positionOfJob, int postionOfTask){
You misspelled `postionOfTask`

2018-10-04 05:19 UTC, leonidscott commented on src/applications/SimulationSpecification.java
> +        return out;
Naming variables is super hard, so don't do it if you don't get anything from it! Just return everything on line 36 on line 36.

2018-10-04 05:19 UTC, leonidscott commented on src/applications/MachineShopSimulator.java
> +                int theMachine = specification.getSpecification(i, 2*(j-1)+1);
Nice!

2018-10-04 05:19 UTC, leonidscott commented on tests/acceptanceTests/applications/FileIoTests.java
> +     *
White space

2018-10-07 21:09 UTC, merged